version: 0.0 
os: linux 
files:
  - source: myhelloworld.js
    destination: /usr/local/myhelloworld/
  - source: scripts/myhelloworld.conf
    destination: /etc/init/
hooks: 
  BeforeInstall: 
    - location: scripts/mystop.sh 
      timeout: 30 
  ApplicationStart:
    - location: scripts/mystart.sh
      timeout: 30
  ValidateService:
    - location: scripts/myvalidate.sh
